### ISSUE TITLE
Timeout on socket - Failed to connect the ip 244.0.0.50

### ISSUE THREAD

**Issue by aferraz** [fooxy/homeassistant-aqara#4]
Hi,
 I have this error:
pyAqara.gateway: Timeout on socket - Failed to connect the ip 244.0.0.50

Can you help me ?

Regards
 Alessandro

**Comment by aferraz** [comment]
After the update i break all my config :-(

**Comment by fooxy** [comment]
Hi,

Some times it happens just reboot / restart home-assistant.
Hope it will work.

**Comment by aferraz** [comment]
Hi,
 same error after restart has and system reboot also.

Regards
 Alessandro

**Comment by fooxy** [comment]
Could you share your home-assistant.log and configuration.yaml.
Thanks.

**Comment by aferraz** [comment]
[configuration.zip](https://github.com/fooxy/homeassistant-aqara/files/667020/configuration.zip)

**Comment by aferraz** [comment]
Hi fooxy,
 sorry it is a gateway problem. If I restart the xiaomi gateway your plugin work. Thanks.

Regards
 Alessandro
