### ISSUE TITLE
 Error during setup of component aqara

### ISSUE THREAD

**Issue by DenneyTang** [fooxy/homeassistant-aqara#5]
I got this  error...

--------------------

16-12-21 16:23:14 homeassistant.bootstrap: Error during setup of component aqara
Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/aqara.py", line 23, in setup
    gateway.initGateway()
  File "/home/homeassistant/.homeassistant/deps/pyAqara/gateway.py", line 50, in initGateway
    self.socket = self._prepare_socket()
  File "/home/homeassistant/.homeassistant/deps/pyAqara/gateway.py", line 118, in _prepare_socket
    sock.bind(("0.0.0.0", self.MULTICAST_PORT))
OSError: [Errno 98] Address already in use

**Comment by fooxy** [comment]
I had this error with my raspberry pi but not with osx.
I've done some modification, it should work now.

But if the udp port 9898 is used by another app, the issue will remain.

I hope it will be ok.

**Comment by DenneyTang** [comment]
Sorry for my bad English...  I had Homebridge(emulates the iOS HomeKit API ：https://github.com/nfarina/homebridge)  run on my raspberry pi . Homebridge  used udp port 9898... Any solution?

**Comment by DenneyTang** [comment]
And this :https://github.com/snOOrz/homebridge-aqara

**Comment by fooxy** [comment]
- remove or disable homeridge-aqara
- reboot
- use instead this : [https://github.com/home-assistant/homebridge-homeassistant](url)
I think it should work.

**Comment by DenneyTang** [comment]
Great！！ it's work HAHA!
Thanks very much!
